# site settings
title: Homepage
# subtitle: by HTML5 UP
email: zhang@hlab.sys.es.osaka-u.ac.jp
description: A Ph.D candidate majored in Robotics <br /> at Osaka University.
baseurl: "/zhangOSK.github.io" # the subpath of your site, e.g. /blog
url: https://zhangosk.github.io/ # the base hostname & protocol for your site
author:
street_address: Department of System Innovation, Graduate School of Engineering Science, Osaka University
city: Toyonaka City
state: Osaka
zip_code: 560-0043
country: Japan
#phone: (716) 555-5555

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 3

# social settings
500px_url:
facebook_url:
github_url: https://github.com/zhangOSK
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: 
pinterest_url:
slack_url:
# twitter_url: https://twitter.com/andrewbanchich

# build settings
markdown: kramdown

sass:
  style: compressed
